#!/usr/bin/python
# -*- coding: utf-8 -*-

bad = ["haelt", "sicher", "tritt", "essen", "rein",
       "sich", "offen", "Leute", "Fuenf", "echt",
       "legt", "laenger", "zeigt", "lang", "gibt",
       "Woche", "Jahren", "kein", "euch", "Kein",
       "eine", "muss", "oben", "haben",
       "laesst", "startet", "Video", "unter", "here", "drei", "gehen",
       "wird", "Eine", "allen", "Geri",
       "sind", "auch", "+++:", "einen", "fahren",
       "nicht", "noch", "ohne", "seit", "letzte", "Drei", "Unter", "Wochen",
       "Diese", "diese", "immer", "einer", "bring", "erste",
       "Neue", "nach", "fuer", "ueber", "frei", "macht",
       "UeBERSICHT", "unter", "will", "Ueber", "alte", "keine",
       "Zwei","zwei", "alle", "eins", "Nach", "holt",
       "weiter", "mein", "Deutschland", "nehmen",
       "Internet:", "Sport", "mehr", "Mehr", "soll", "durch",
       "kommt", "zurueck", "halt", "erst", "acht", "aller", "raus", "Keine", 
       "beste", "Ukraine-", "geben", "geben", "machen", "Tuer", "fest",
       "wegen", "Fußball", "gegen", "kann", 
       "dies", "geht", "Auto", "neue", "aufs", "oder",
       "echte", "Wind", "werde", "Tage", "2014", "reist", "werden", 
       "Meter", "meist", "Wenn", "habe", "Groß", "wieder", "stand", "große",
       "Jahr", "heim", "weit", "deutsche", "Frau", "Zeit", "Familie", "Liebe",
       "beim", "Erst", "Komm", "eines", "ihre", "Haus", "\"Ich", "Mann", "kommen",
       "teil", "teilt", "eure", "hart", "Welt", "Fuss", "mach", "eben",
       "neuen", "Hand", "Warum", "Alle", "lange", "seine", "koennte", "gemein",
       "zweites", "alten", "sucht", "\"Die", "vier", "fuenf", "voll", "andere",
       "einem", "muessen", "Klaus", "statt", "Will", "fort", "fort", "gleich",
       "wollen", "aber", "neuer", "Ende", "muessen", "bringt", "statt", "setzt",
       "enden", "viel", "Ende", "plant", "bringt", "Nachrichten", "droht", 
       "Arme", "statt", "setzt", "ganz", "Deutsch", "gebe", "eher", "steht",
       "sehen", "gehe", "eher", "sieht", "\"Das", "jede", "denken", "stark",
       "Drei-", "komme", "jetzt", "bitte", "lassen", "rund", "stellt", "Frank",
       "doch", "nimmt", "Viel", "sechs", "Vier", "sagt", "lass", "Wiesn",
       "Erste", "Voll", "reich", "rote", "renn", "ringt", "einig",
       "enge", "start", "bereit", "Miss", "zieht", "ieder", "hatte",
       "Spiele", "League", "Fussball", "Champions", "Allgemein", "schon",
       "erhoeht", "warnt", "Nord", "ruck", "Profi", "ersten", "Fussball:",
       "liess", "ausser", "erneut", "feiert", "spielt", "Moto", "euer",
       "Star", "Neues", "bleibt", "bitten", "fordert", "West", "dass",
       "weitere", "siegt", "achte", "Gross", "Sued", "verlaesst",
       "Zustand", "sollen", "lame", "faellt", "Eins", "laut", "Mass",
       "darf", "meiste", "Deutsche", "teuer", "Bund", "spaet", "Neuer",
       "Kommentar", "Recht", "ehrt", "spaet", "Grund", "Ein-", "Bode", 
       "ordnet", "sehe", "enger", "erstmals", "endet", "willige", 
       "ordnet", "trotz", "enger", "sehe", "ante", "Auch", "morgen",
       "fuehren", "schwarze", "Aufs", "Bahn-", "griff", "wert", "zahlen",
       "nich", "Mens", "eiert" , "ruft", "gross"]

exception = ["EU", "Eu", "USA", "BND", "IS", "Tod", "CIA", "NSA", "ARD", "ZDF",
	   		 "Uni", "UNI", "UNO", "CDU", "CSU", "SPD", "AFD", "Afd", "FDP", "Uno", "BMW",
	   		 "PKK", "Dax", "DAX"]
